from metagpt.actions import Action


class PrintTwo(Action):
    name: str = "print the second"
    content: str = ""
    language: str = "germany"

    async def run(self, content: str, *args, **kwargs):
        PRINT_PROMPT = """
        You are the print writer, we need you run the two action to print the content.
        """

        PRINT_CONTENT = PRINT_PROMPT + """
        Now I will give you the content, this content is generated by the first print action, please use {language} to 
        translate it and print it:{content}
        """

        prompt = PRINT_CONTENT.format(content=content, language=self.language)
        return await self._aask(prompt=prompt)